### ISSUE TITLE
Problem with play next mp3 file and pause/play/stop spinner

### ISSUE THREAD

**Issue by ghost** [christophecvr/gstreamer1.0-plugin-multibox-dvbmediasink#33]
see: http://www.opena.tv/mut-nt-hd51/29129-player-probleme-nach-update.html#post257371
or : http://www.opena.tv/xtrend-et9200/22694-media-center-media-player-spielen-keine-mp3-dateien-mehr-ab-post256416.html#post256416
or: http://www.opena.tv/world-vision-force-1-a/29009-mediaplayer.html?highlight=spinner
...

Edit:  Only this one change causes these problems.

`992   -#if defined(__sh__) && !defined(CHECK_DRAIN)`
`1001 +#ifndef CHECK_DRAIN`

Please check your last commit.

**Comment by christophecvr** [comment]
The point mentioned is reverted to sh4 only.

should be ok now

**Comment by christophecvr** [comment]
small note,
on dm8000 all 100 %. Just noticed that vuduo2 still suffers but less from sandkeeper with mp3 audio and flac audio codecs . The other needs revert for audio also bussy with it.

**Comment by ghost** [comment]
Thank you for your work. :)
